Repository luoxuhai/pcl.js, pull requests merged in 2022-10, with the labels that each got.

#56 fix: unable to use new point type
  src/bind/build/pcl-core.js
  src/bind/build/pcl-core.wasm
  src/bind/embind.hpp
Labels: bug

#63 feat: add SACSegmentation
  data/noisy_slice_displaced.pcd
  src/bind/build/pcl-core.js
  src/bind/build/pcl-core.wasm
  src/bind/common.cpp
  src/bind/sample_consensus.cpp
  src/bind/segmentation.cpp
  src/core/index.ts
  src/modules/common/ModelCoefficients.ts
  src/modules/common/PCLBase.ts
  src/modules/common/PointCloud.ts
  src/modules/common/index.ts
  src/modules/common/utils.ts
  src/modules/sample-consensus/constants.ts
  src/modules/sample-consensus/index.ts
  src/modules/segmentation/SACSegmentation.ts
  src/modules/segmentation/index.ts
  tests/segmentation/SACSegmentation.test.ts
  website/docs/api/segmentation/sac-segmentation.md
  website/docs/api/utils.md
Labels: enhancement

#69 feat: add SampleConsensusInitialAlignment api
  data/bun4.pcd
  src/bind/build/pcl-core.js
  src/bind/build/pcl-core.wasm
  src/bind/embind.hpp
  src/bind/features.cpp
  src/bind/point_types.cpp
  src/bind/registration.cpp
  src/bind/segmentation.cpp
  src/core/index.ts
  src/modules/common/PointCloud.ts
  src/modules/common/point-types.ts
  src/modules/features/FPFHEstimation.ts
  src/modules/features/Feature.ts
  src/modules/features/FeatureFromNormals.ts
  src/modules/features/NormalEstimation.ts
  src/modules/features/index.ts
  src/modules/registration/IterativeClosestPoint.ts
  src/modules/registration/Registration.ts
  src/modules/registration/SampleConsensusInitialAlignment.ts
  src/modules/registration/index.ts
  src/modules/segmentation/SACSegmentation.ts
  tests/registration/IterativeClosestPoint.test.ts
  tests/registration/SampleConsensusInitialAlignment.test.ts
  tests/utils.ts
Labels: feature request, in progress
